-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 10:25:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `RecordCompany Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RecordCompany Table` (
  `RecordCompany` INT NOT NULL,
  `RecordCompanyName` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RecordCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Album Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Album Table` (
  `AlbumID` INT NOT NULL,
  `AlbumTitle` VARCHAR(45) NOT NULL,
  `Rating` INT NULL,
  `RecordCompanyID` INT NOT NULL,
  PRIMARY KEY (`AlbumID`),
  INDEX `fk_Album Table_RecordCompany Table1_idx` (`RecordCompanyID` ASC) VISIBLE,
  CONSTRAINT `fk_Album Table_RecordCompany Table1`
    FOREIGN KEY (`RecordCompanyID`)
    REFERENCES `RecordCompany Table` (`RecordCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Song` (
  `SongID` INT NOT NULL,
  `SongTitle` VARCHAR(45) NOT NULL,
  `Artist` VARCHAR(45) NOT NULL,
  `AlbumID` INT NULL,
  `LastPlayed` DATETIME NULL,
  `Genre` VARCHAR(20) NULL,
  PRIMARY KEY (`SongID`),
  INDEX `fk_Song_Album Table_idx` (`AlbumID` ASC) VISIBLE,
  CONSTRAINT `fk_Song_Album Table`
    FOREIGN KEY (`AlbumID`)
    REFERENCES `Album Table` (`AlbumID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
